# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ec23bbd3ec5198aedf18fa5f40036f83"
name = "app-test-joy"
application_url = "https://byte-correction-gorgeous-fold.trycloudflare.com"
embedded = true
handle = "app-test-joy"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_content,read_customers,read_discounts,read_fulfillments,read_orders,read_payment_terms,read_products,write_app_proxy,write_discounts,write_files,write_fulfillments,write_orders,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://byte-correction-gorgeous-fold.trycloudflare.com/auth/callback",
  "https://byte-correction-gorgeous-fold.trycloudflare.com/auth/shopify/callback",
  "https://byte-correction-gorgeous-fold.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://byte-correction-gorgeous-fold.trycloudflare.com"
subpath = "kazi-proxy"
prefix = "apps"

[pos]
embedded = false
